# Generated by Django 6.0.6 on 2026-06-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aluno_emprestimo_delete_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
